version: '3'

services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      - database
      - minio
    networks:
      - GrafhyPy

  minio:
    image: docker.io/bitnami/minio:2023
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=your_username
      - MINIO_ROOT_PASSWORD=your_pasword
      - MINIO_DEFAULT_BUCKETS=grafhy
    volumes:
      - minio_data:/data
    networks:
      - GrafhyPy
    
  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - GrafhyPy

  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grafhyPy
    volumes:
      - ./server/banco.sql:/docker-entrypoint-initdb.d/banco.sql
    networks:
      - GrafhyPy

networks:
  GrafhyPy:

volumes:
  minio_data:
